inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

Airbnb/OptArgParameters:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false


AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
